import { Scenario, ScenarioStep } from "../types";

interface PostmanItem {
  name: string;
  request: {
    method: string;
    header: Array<{ key: string; value: string }>;
    url: { raw: string; host: string[]; path: string[] };
    body?: { mode: string; raw: string };
  };
  event?: Array<{ listen: string; script: { exec: string[] } }>;
}

export function exportToPostman(scenario: Scenario, baseUrl: string): string {
  const items: PostmanItem[] = scenario.steps.map((step, index) => {
    const url = `${baseUrl}${step.path}`;
    const urlParts = url.replace(/^https?:\/\//, "").split("/");

    const item: PostmanItem = {
      name: step.description || `Step ${index + 1}: ${step.method} ${step.path}`,
      request: {
        method: step.method,
        header: Object.entries(step.headers).map(([key, value]) => ({ key, value })),
        url: {
          raw: url,
          host: [urlParts[0]],
          path: urlParts.slice(1),
        },
      },
    };

    if (step.body) {
      item.request.body = {
        mode: "raw",
        raw: JSON.stringify(step.body, null, 2),
      };
    }

    if (step.extractVariables && Object.keys(step.extractVariables).length > 0) {
      const scripts: string[] = [];
      for (const [varName, jsonPath] of Object.entries(step.extractVariables)) {
        scripts.push(
          `const response = pm.response.json();`,
          `pm.collectionVariables.set("${varName}", response.${jsonPath});`
        );
      }
      item.event = [{ listen: "test", script: { exec: scripts } }];
    }

    return item;
  });

  const collection = {
    info: {
      name: scenario.name,
      description: scenario.description || "",
      schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
      _postman_id: scenario.id,
    },
    item: items,
  };

  return JSON.stringify(collection, null, 2);
}

export function exportToPlaywright(scenario: Scenario, baseUrl: string): string {
  const steps = scenario.steps.map((step, index) => {
    const headers = Object.entries(step.headers)
      .map(([k, v]) => `      "${k}": "${v}"`)
      .join(",\n");

    let bodyStr = "";
    if (step.body) {
      bodyStr = `,\n      data: ${JSON.stringify(step.body, null, 6).split("\n").join("\n      ")}`;
    }

    let expectStr = `  expect(response.status()).toBe(${step.expectedStatus});`;
    if (step.extractVariables && Object.keys(step.extractVariables).length > 0) {
      const extracts = Object.entries(step.extractVariables)
        .map(([varName, jsonPath]) => {
          const pathParts = jsonPath.split(".");
          const accessExpr = pathParts.map(p => `["${p}"]`).join("");
          return `  const ${varName} = (await response.json())${accessExpr};`;
        })
        .join("\n");
      expectStr = `${extracts}\n${expectStr}`;
    }

    return `
  // Step ${index + 1}: ${step.description || step.method + " " + step.path}
  const response${index} = await request.${step.method.toLowerCase()}(\`${baseUrl}${step.path}\`, {
    headers: {
${headers}
    }${bodyStr}
  });
${expectStr}`;
  });

  return `import { test, expect, request } from "@playwright/test";

test("${scenario.name}", async ({ }) => {
  const request = await request.newContext();
${steps.join("\n")}
});
`;
}

export function exportToCurl(scenario: Scenario, baseUrl: string): string {
  const commands = scenario.steps.map((step, index) => {
    const headerFlags = Object.entries(step.headers)
      .map(([k, v]) => `  -H '${k}: ${v}'`)
      .join(" \\\n");

    const bodyFlag = step.body
      ? `  -H 'Content-Type: application/json' \\\n  -d '${JSON.stringify(step.body)}'`
      : "";

    const parts = [
      `# Step ${index + 1}: ${step.description || step.method + " " + step.path}`,
      `curl -X ${step.method} \\\n  '${baseUrl}${step.path}'`,
    ];

    if (headerFlags) parts.push(headerFlags);
    if (bodyFlag) parts.push(bodyFlag);

    return parts.join(" \\\n");
  });

  return `#!/bin/bash
# Scenario: ${scenario.name}
# Description: ${scenario.description || "N/A"}
# Generated by SchemaDrome

set -e

${commands.join("\n\n")}
`;
}

export function exportScenario(scenario: Scenario, format: "postman" | "playwright" | "curl", baseUrl: string): { content: string; contentType: string; filename: string } {
  switch (format) {
    case "postman":
      return {
        content: exportToPostman(scenario, baseUrl),
        contentType: "application/json",
        filename: `${scenario.name.replace(/\s+/g, "-").toLowerCase()}.postman_collection.json`,
      };
    case "playwright":
      return {
        content: exportToPlaywright(scenario, baseUrl),
        contentType: "text/typescript",
        filename: `${scenario.name.replace(/\s+/g, "-").toLowerCase()}.spec.ts`,
      };
    case "curl":
      return {
        content: exportToCurl(scenario, baseUrl),
        contentType: "text/x-shellscript",
        filename: `${scenario.name.replace(/\s+/g, "-").toLowerCase()}.sh`,
      };
  }
}
